apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secret
  namespace: employee-management-app
type: Opaque
stringData:
  MONGO_URI: mongodb://mady-thikse:Mady321@mongo:27017/employeedb?authSource=admin