apiVersion: v1
kind: Secret
metadata:
  name: employee-app-secret
  namespace: employee-management-app
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:changeme@mongo:27017/employeedb?authSource=admin