apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: employee-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app
          image: raiden004/employee-api:v1.2
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: employee-app-config
                  key: PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: employee-app-secret
                  key: MONGO_URI
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10