$BaseUrl = "http://15.207.235.143:30950/api/employees"

$employees = @(
    @{ name = "Ananya Rao"; email = "ananya.rao@techflux.io"; department = "Engineering"; role = "Backend Developer"; salary = 78000 },
    @{ name = "Marcus Chen"; email = "marcus.chen@brightgrid.com"; department = "Product"; role = "Product Manager"; salary = 92000 },
    @{ name = "Priya Nair"; email = "priya.nair@vertexlabs.co"; department = "Design"; role = "UI/UX Designer"; salary = 68000 },
    @{ name = "Daniel Osei"; email = "daniel.osei@nimbuscore.net"; department = "DevOps"; role = "Site Reliability Engineer"; salary = 88000 },
    @{ name = "Sofia Martinez"; email = "sofia.martinez@quantaworks.com"; department = "Sales"; role = "Account Executive"; salary = 71000 },
    @{ name = "Rahul Verma"; email = "rahul.verma@stackhive.io"; department = "Engineering"; role = "Frontend Developer"; salary = 74000 },
    @{ name = "Emily Zhang"; email = "emily.zhang@corelynx.co"; department = "HR"; role = "HR Business Partner"; salary = 65000 },
    @{ name = "Kwame Boateng"; email = "kwame.boateng@ironloop.com"; department = "Finance"; role = "Financial Analyst"; salary = 70000 },
    @{ name = "Isabella Rossi"; email = "isabella.rossi@fluxbyte.net"; department = "Marketing"; role = "Marketing Lead"; salary = 76000 },
    @{ name = "Arjun Mehta"; email = "arjun.mehta@pivotforge.io"; department = "Engineering"; role = "DevOps Engineer"; salary = 85000 },
    @{ name = "Olivia Bennett"; email = "olivia.bennett@cloudanchor.dev"; department = "Engineering"; role = "Cloud Engineer"; salary = 89000 },
    @{ name = "Wei Zhang"; email = "wei.zhang@synapsehub.ai"; department = "Data"; role = "Data Scientist"; salary = 95000 },
    @{ name = "Fatima Al-Sayed"; email = "fatima.alsayed@brickwaveco.com"; department = "Operations"; role = "Operations Manager"; salary = 72000 },
    @{ name = "Liam O'Brien"; email = "liam.obrien@northgatetech.io"; department = "Engineering"; role = "Platform Engineer"; salary = 83000 },
    @{ name = "Chiara Ferrari"; email = "chiara.ferrari@lumenpixel.co"; department = "Design"; role = "Graphic Designer"; salary = 62000 },
    @{ name = "Tariq Hussain"; email = "tariq.hussain@ridgebackdata.com"; department = "Data"; role = "Data Engineer"; salary = 87000 },
    @{ name = "Grace Kim"; email = "grace.kim@velvethill.net"; department = "Legal"; role = "Legal Counsel"; salary = 99000 },
    @{ name = "Noah Fischer"; email = "noah.fischer@cinderforge.de"; department = "Engineering"; role = "Security Engineer"; salary = 91000 },
    @{ name = "Amara Chukwu"; email = "amara.chukwu@savannastack.io"; department = "Product"; role = "Product Analyst"; salary = 69000 },
    @{ name = "Hiroshi Tanaka"; email = "hiroshi.tanaka@kaidenlabs.jp"; department = "Engineering"; role = "Mobile Developer"; salary = 80000 },
    @{ name = "Elena Popescu"; email = "elena.popescu@driftwoodhq.com"; department = "Marketing"; role = "Content Strategist"; salary = 63000 },
    @{ name = "Samuel Okafor"; email = "samuel.okafor@pinehavendigital.co"; department = "Sales"; role = "Sales Manager"; salary = 84000 },
    @{ name = "Julia Andersson"; email = "julia.andersson@nordicframe.se"; department = "Design"; role = "Product Designer"; salary = 75000 },
    @{ name = "Ravi Shankar"; email = "ravi.shankar@emberlinetech.io"; department = "Engineering"; role = "QA Engineer"; salary = 67000 },
    @{ name = "Camille Dubois"; email = "camille.dubois@bellecraftco.fr"; department = "HR"; role = "Talent Acquisition Lead"; salary = 66000 },
    @{ name = "Ethan Walker"; email = "ethan.walker@granitepeakdev.com"; department = "Engineering"; role = "Full Stack Developer"; salary = 82000 },
    @{ name = "Nadia Ivanova"; email = "nadia.ivanova@birchrowlabs.io"; department = "Finance"; role = "Finance Manager"; salary = 93000 },
    @{ name = "Lucas Silva"; email = "lucas.silva@copperlinetech.com.br"; department = "DevOps"; role = "Cloud Architect"; salary = 97000 },
    @{ name = "Meera Pillai"; email = "meera.pillai@sundialworks.co"; department = "Product"; role = "Scrum Master"; salary = 73000 },
    @{ name = "Adam Nowak"; email = "adam.nowak@ashgrovesystems.pl"; department = "Engineering"; role = "Backend Developer"; salary = 77000 },
    @{ name = "Yuki Sato"; email = "yuki.sato@momijitech.jp"; department = "Design"; role = "Interaction Designer"; salary = 71000 },
    @{ name = "Victor Alvarez"; email = "victor.alvarez@redstonelabs.mx"; department = "Operations"; role = "Logistics Coordinator"; salary = 59000 },
    @{ name = "Hannah Schmidt"; email = "hannah.schmidt@falkenreach.de"; department = "HR"; role = "HR Generalist"; salary = 61000 },
    @{ name = "Ibrahim Diallo"; email = "ibrahim.diallo@baobabventures.io"; department = "Sales"; role = "Business Development Rep"; salary = 64000 },
    @{ name = "Charlotte Evans"; email = "charlotte.evans@willowbrookco.com"; department = "Legal"; role = "Compliance Officer"; salary = 86000 },
    @{ name = "Dmitri Volkov"; email = "dmitri.volkov@ironbirchtech.ru"; department = "Engineering"; role = "Systems Engineer"; salary = 90000 },
    @{ name = "Aaliyah Johnson"; email = "aaliyah.johnson@brightfernco.com"; department = "Marketing"; role = "SEO Specialist"; salary = 58000 },
    @{ name = "Mateus Costa"; email = "mateus.costa@vinehollowdev.com.br"; department = "Engineering"; role = "DevOps Engineer"; salary = 81000 },
    @{ name = "Zoe Papadopoulos"; email = "zoe.papadopoulos@aegeandrift.gr"; department = "Design"; role = "Brand Designer"; salary = 64000 },
    @{ name = "Karim Farouk"; email = "karim.farouk@duneforgetech.eg"; department = "Data"; role = "Analytics Engineer"; salary = 88000 },
        @{ name = 'Esme Haddad'; email = "esme.haddad@techflux.io"; department = "Engineering"; role = "Frontend Developer"; salary = 72000 },
    @{ name = 'Femi Okafor'; email = "femi.okafor@brightgrid.com"; department = "DevOps"; role = "DevOps Engineer"; salary = 61000 },
    @{ name = 'Jinho Vargas'; email = "jinho.vargas@vertexlabs.co"; department = "Operations"; role = "Operations Manager"; salary = 60000 },
    @{ name = 'Yelena Bianchi'; email = "yelena.bianchi@nimbuscore.net"; department = "Engineering"; role = "Full Stack Developer"; salary = 56000 },
    @{ name = 'Layla Nowak'; email = "layla.nowak@quantaworks.com"; department = "Product"; role = "Product Manager"; salary = 87000 },
    @{ name = 'Amara Bergman'; email = "amara.bergman@stackhive.io"; department = "Operations"; role = "Logistics Coordinator"; salary = 67000 },
    @{ name = 'Olive Petersen'; email = "olive.petersen@corelynx.co"; department = "Operations"; role = "Operations Manager"; salary = 81000 },
    @{ name = 'Celine Costa'; email = "celine.costa@ironloop.com"; department = "Design"; role = "UI/UX Designer"; salary = 55000 },
    @{ name = 'Ursula Adeyemi'; email = "ursula.adeyemi@fluxbyte.net"; department = "DevOps"; role = "Site Reliability Engineer"; salary = 99000 },
    @{ name = 'Dev Vance'; email = "dev.vance@pivotforge.io"; department = "Design"; role = "UI/UX Designer"; salary = 64000 },
    @{ name = 'Bruno Wong'; email = "bruno.wong@cloudanchor.dev"; department = "Sales"; role = "Account Executive"; salary = 61000 },
    @{ name = 'Layla Yilmaz'; email = "layla.yilmaz@synapsehub.ai"; department = "Engineering"; role = "Mobile Developer"; salary = 77000 },
    @{ name = 'Sven Moreno'; email = "sven.moreno@brickwaveco.com"; department = "Product"; role = "Scrum Master"; salary = 57000 },
    @{ name = 'Qamar Dahl'; email = "qamar.dahl@northgatetech.io"; department = "Operations"; role = "Operations Manager"; salary = 62000 },
    @{ name = 'Wesley Farah'; email = "wesley.farah@lumenpixel.co"; department = "Operations"; role = "Logistics Coordinator"; salary = 73000 },
    @{ name = 'Dorian Nilsson'; email = "dorian.nilsson@ridgebackdata.com"; department = "Sales"; role = "Business Development Rep"; salary = 91000 },
    @{ name = 'Yusuf Thorne'; email = "yusuf.thorne@velvethill.net"; department = "Engineering"; role = "Security Engineer"; salary = 57000 },
    @{ name = 'Hassan Okafor'; email = "hassan.okafor@cinderforge.de"; department = "Design"; role = "Product Designer"; salary = 60000 },
    @{ name = 'Dmitri Elmasry'; email = "dmitri.elmasry@savannastack.io"; department = "Engineering"; role = "Mobile Developer"; salary = 79000 },
    @{ name = 'Jamal Dahl'; email = "jamal.dahl@kaidenlabs.jp"; department = "Sales"; role = "Business Development Rep"; salary = 65000 },
    @{ name = 'Valeria Weber'; email = "valeria.weber@driftwoodhq.com"; department = "Data"; role = "Analytics Engineer"; salary = 97000 },
    @{ name = 'Inez Silva'; email = "inez.silva@pinehavendigital.co"; department = "Engineering"; role = "Security Engineer"; salary = 93000 },
    @{ name = 'Esme Kowalski'; email = "esme.kowalski@nordicframe.se"; department = "Operations"; role = "Operations Manager"; salary = 70000 },
    @{ name = 'Uma Dahl'; email = "uma.dahl@emberlinetech.io"; department = "Marketing"; role = "Marketing Lead"; salary = 72000 },
    @{ name = 'Esme Silva'; email = "esme.silva@bellecraftco.fr"; department = "Operations"; role = "Logistics Coordinator"; salary = 69000 },
    @{ name = 'Kaia Ueda'; email = "kaia.ueda@granitepeakdev.com"; department = "Engineering"; role = "QA Engineer"; salary = 69000 },
    @{ name = 'Ezra Adeyemi'; email = "ezra.adeyemi@birchrowlabs.io"; department = "Design"; role = "Interaction Designer"; salary = 80000 },
    @{ name = 'Inez Eriksson'; email = "inez.eriksson@copperlinetech.com.br"; department = "Data"; role = "Analytics Engineer"; salary = 91000 },
    @{ name = 'Olive Ueda'; email = "olive.ueda@sundialworks.co"; department = "Data"; role = "Analytics Engineer"; salary = 96000 },
    @{ name = 'Miriam Zeller'; email = "miriam.zeller@ashgrovesystems.pl"; department = "HR"; role = "Talent Acquisition Lead"; salary = 64000 },
    @{ name = 'Hugo Ibsen'; email = "hugo.ibsen@momijitech.jp"; department = "Product"; role = "Product Analyst"; salary = 90000 },
    @{ name = 'Rafael Quintero'; email = "rafael.quintero@redstonelabs.mx"; department = "HR"; role = "HR Business Partner"; salary = 92000 },
    @{ name = 'Anya Xu'; email = "anya.xu@falkenreach.de"; department = "Product"; role = "Product Manager"; salary = 63000 },
    @{ name = 'Odette Fischer'; email = "odette.fischer@baobabventures.io"; department = "Engineering"; role = "Systems Engineer"; salary = 58000 },
    @{ name = 'Oscar Jansen'; email = "oscar.jansen@willowbrookco.com"; department = "DevOps"; role = "Site Reliability Engineer"; salary = 98000 },
    @{ name = 'Dev Moreno'; email = "dev.moreno@ironbirchtech.ru"; department = "Engineering"; role = "Security Engineer"; salary = 79000 },
    @{ name = 'Wesley Moreno'; email = "wesley.moreno@brightfernco.com"; department = "HR"; role = "Talent Acquisition Lead"; salary = 88000 },
    @{ name = 'Greta Jorgensen'; email = "greta.jorgensen@vinehollowdev.com.br"; department = "Engineering"; role = "Backend Developer"; salary = 98000 },
    @{ name = 'Petra Haddad'; email = "petra.haddad@aegeandrift.gr"; department = "Operations"; role = "Operations Manager"; salary = 72000 },
    @{ name = 'Vasco Petersen'; email = "vasco.petersen@duneforgetech.eg"; department = "Sales"; role = "Account Executive"; salary = 62000 },
    @{ name = 'Leon Bianchi'; email = "leon.bianchi@solisware.com"; department = "DevOps"; role = "Site Reliability Engineer"; salary = 84000 },
    @{ name = 'Aiden Ulloa'; email = "aiden.ulloa@tundragate.io"; department = "Product"; role = "Scrum Master"; salary = 87000 },
    @{ name = 'Ursula Larsson'; email = "ursula.larsson@maplecresttech.ca"; department = "Legal"; role = "Legal Counsel"; salary = 61000 },
    @{ name = 'Dorian Tanaka'; email = "dorian.tanaka@ashfordbyte.com"; department = "Legal"; role = "Legal Counsel"; salary = 93000 },
    @{ name = 'Zara Jansen'; email = "zara.jansen@kestrelworks.io"; department = "Sales"; role = "Business Development Rep"; salary = 65000 },
    @{ name = 'Sana Yamada'; email = "sana.yamada@techflux.io"; department = "Legal"; role = "Compliance Officer"; salary = 55000 },
    @{ name = 'Ziya Ueda'; email = "ziya.ueda@brightgrid.com"; department = "Finance"; role = "Finance Manager"; salary = 56000 },
    @{ name = 'Oscar Isaacsen'; email = "oscar.isaacsen@vertexlabs.co"; department = "Sales"; role = "Business Development Rep"; salary = 74000 },
    @{ name = 'Elif Dubois'; email = "elif.dubois@nimbuscore.net"; department = "Product"; role = "Product Analyst"; salary = 91000 },
    @{ name = 'Kofi Farah'; email = "kofi.farah@quantaworks.com"; department = "Finance"; role = "Finance Manager"; salary = 59000 },
    @{ name = 'Ursula Ivanov'; email = "ursula.ivanov@stackhive.io"; department = "DevOps"; role = "DevOps Engineer"; salary = 63000 },
    @{ name = 'Hassan Esposito'; email = "hassan.esposito@corelynx.co"; department = "Operations"; role = "Logistics Coordinator"; salary = 65000 },
    @{ name = 'Hugo Holm'; email = "hugo.holm@ironloop.com"; department = "HR"; role = "HR Business Partner"; salary = 68000 },
    @{ name = 'Sana Wong'; email = "sana.wong@fluxbyte.net"; department = "Data"; role = "Data Engineer"; salary = 74000 },
    @{ name = 'Anya Quiroga'; email = "anya.quiroga@pivotforge.io"; department = "Sales"; role = "Business Development Rep"; salary = 83000 },
    @{ name = 'Pablo Costa'; email = "pablo.costa@cloudanchor.dev"; department = "Engineering"; role = "Platform Engineer"; salary = 70000 },
    @{ name = 'Celine Eriksson'; email = "celine.eriksson@synapsehub.ai"; department = "Sales"; role = "Account Executive"; salary = 56000 },
    @{ name = 'Yelena Jorgensen'; email = "yelena.jorgensen@brickwaveco.com"; department = "Product"; role = "Product Manager"; salary = 92000 },
    @{ name = 'Celine Alvarez'; email = "celine.alvarez@northgatetech.io"; department = "Engineering"; role = "Security Engineer"; salary = 95000 },
    @{ name = 'Hana Okafor'; email = "hana.okafor@lumenpixel.co"; department = "Engineering"; role = "Security Engineer"; salary = 57000 },
    @{ name = 'Quan Eriksson'; email = "quan.eriksson@ridgebackdata.com"; department = "Legal"; role = "Legal Counsel"; salary = 70000 },
    @{ name = 'Jamal Quiroga'; email = "jamal.quiroga@velvethill.net"; department = "Finance"; role = "Finance Manager"; salary = 68000 },
    @{ name = 'Sana Ibsen'; email = "sana.ibsen@cinderforge.de"; department = "Finance"; role = "Financial Analyst"; salary = 70000 },
    @{ name = 'Jonas Adeyemi'; email = "jonas.adeyemi@savannastack.io"; department = "Marketing"; role = "SEO Specialist"; salary = 67000 },
    @{ name = 'Mateo Gomez'; email = "mateo.gomez@kaidenlabs.jp"; department = "HR"; role = "HR Business Partner"; salary = 77000 },
    @{ name = 'Dev Andersen'; email = "dev.andersen@driftwoodhq.com"; department = "HR"; role = "Talent Acquisition Lead"; salary = 58000 },
    @{ name = 'Jinho Petersen'; email = "jinho.petersen@pinehavendigital.co"; department = "Engineering"; role = "Mobile Developer"; salary = 58000 },
    @{ name = 'Anya Ulloa'; email = "anya.ulloa@nordicframe.se"; department = "Sales"; role = "Account Executive"; salary = 61000 },
    @{ name = 'Femi Mensah'; email = "femi.mensah@emberlinetech.io"; department = "Data"; role = "Data Engineer"; salary = 89000 },
    @{ name = 'Giulia Ibsen'; email = "giulia.ibsen@bellecraftco.fr"; department = "HR"; role = "HR Business Partner"; salary = 66000 },
    @{ name = 'Femi Elmasry'; email = "femi.elmasry@granitepeakdev.com"; department = "Engineering"; role = "Security Engineer"; salary = 83000 },
    @{ name = 'Theo Gomez'; email = "theo.gomez@birchrowlabs.io"; department = "Engineering"; role = "QA Engineer"; salary = 96000 },
    @{ name = 'Sana Chowdhury'; email = "sana.chowdhury@copperlinetech.com.br"; department = "Engineering"; role = "Backend Developer"; salary = 60000 },
    @{ name = 'Taj Dumont'; email = "taj.dumont@sundialworks.co"; department = "Product"; role = "Product Analyst"; salary = 65000 },
    @{ name = 'Boris Fischer'; email = "boris.fischer@ashgrovesystems.pl"; department = "Finance"; role = "Financial Analyst"; salary = 68000 },
    @{ name = 'Anya Gustafsson'; email = "anya.gustafsson@momijitech.jp"; department = "Engineering"; role = "QA Engineer"; salary = 65000 },
    @{ name = 'Wesley Alvarez'; email = "wesley.alvarez@redstonelabs.mx"; department = "Marketing"; role = "Marketing Lead"; salary = 71000 },
    @{ name = 'Henrik Sato'; email = "henrik.sato@falkenreach.de"; department = "HR"; role = "HR Business Partner"; salary = 99000 },
    @{ name = 'Qamar Zimmer'; email = "qamar.zimmer@baobabventures.io"; department = "Operations"; role = "Logistics Coordinator"; salary = 97000 },
    @{ name = 'Olive Fischer'; email = "olive.fischer@willowbrookco.com"; department = "DevOps"; role = "Cloud Architect"; salary = 67000 },
    @{ name = 'Leon Nowak'; email = "leon.nowak@ironbirchtech.ru"; department = "Engineering"; role = "QA Engineer"; salary = 92000 },
    @{ name = 'Ronan Ivanov'; email = "ronan.ivanov@brightfernco.com"; department = "Engineering"; role = "QA Engineer"; salary = 75000 },
    @{ name = 'Hana Dubois'; email = "hana.dubois@vinehollowdev.com.br"; department = "Finance"; role = "Financial Analyst"; salary = 87000 },
    @{ name = 'Qadir Kowalski'; email = "qadir.kowalski@aegeandrift.gr"; department = "Engineering"; role = "QA Engineer"; salary = 87000 },
    @{ name = 'Kofi Dumont'; email = "kofi.dumont@duneforgetech.eg"; department = "Data"; role = "Data Scientist"; salary = 59000 },
    @{ name = 'Ziya Eriksson'; email = "ziya.eriksson@solisware.com"; department = "Product"; role = "Product Analyst"; salary = 80000 },
    @{ name = 'Priya Fontaine'; email = "priya.fontaine@tundragate.io"; department = "Product"; role = "Product Analyst"; salary = 92000 },
    @{ name = 'Ziya Cho'; email = "ziya.cho@maplecresttech.ca"; department = "Engineering"; role = "Systems Engineer"; salary = 81000 },
    @{ name = 'Hassan Lindqvist'; email = "hassan.lindqvist@ashfordbyte.com"; department = "Legal"; role = "Compliance Officer"; salary = 75000 },
    @{ name = 'Hugo Nowak'; email = "hugo.nowak@kestrelworks.io"; department = "Design"; role = "Interaction Designer"; salary = 70000 },
    @{ name = 'Hugo Zeller'; email = "hugo.zeller@techflux.io"; department = "DevOps"; role = "DevOps Engineer"; salary = 97000 },
    @{ name = 'Faisal Tanaka'; email = "faisal.tanaka@brightgrid.com"; department = "HR"; role = "Talent Acquisition Lead"; salary = 75000 },
    @{ name = 'Taj Isaacsen'; email = "taj.isaacsen@vertexlabs.co"; department = "Engineering"; role = "Security Engineer"; salary = 55000 },
    @{ name = 'Henrik Nilsson'; email = "henrik.nilsson@nimbuscore.net"; department = "Engineering"; role = "Mobile Developer"; salary = 59000 },
    @{ name = 'Rafael Nowak'; email = "rafael.nowak@quantaworks.com"; department = "Legal"; role = "Legal Counsel"; salary = 71000 },
    @{ name = 'Quinn Isaacsen'; email = "quinn.isaacsen@stackhive.io"; department = "Sales"; role = "Sales Manager"; salary = 59000 },
    @{ name = 'Femi Xu'; email = "femi.xu@corelynx.co"; department = "Design"; role = "Product Designer"; salary = 65000 },
    @{ name = 'Farid Chowdhury'; email = "farid.chowdhury@ironloop.com"; department = "Operations"; role = "Operations Manager"; salary = 74000 },
    @{ name = 'Bashir Adeyemi'; email = "bashir.adeyemi@fluxbyte.net"; department = "Legal"; role = "Compliance Officer"; salary = 55000 },
    @{ name = 'Ingrid Bello'; email = "ingrid.bello@pivotforge.io"; department = "Operations"; role = "Logistics Coordinator"; salary = 74000 }
)

foreach ($emp in $employees) {
    $body = $emp | ConvertTo-Json
    try {
        $response = Invoke-RestMethod -Uri $BaseUrl -Method Post -ContentType "application/json" -Body $body
        Write-Host "Created: $($emp.name)" -ForegroundColor Green
    } catch {
        Write-Host "Failed: $($emp.name) - $($_.Exception.Message)" -ForegroundColor Red
    }
}